config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'

  resources :labs

  resources :devices

  resources :employees

  resources :lendings
  resources :lenders  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'employees_controller#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    attr_accessor :remember_token   
    before_save { self.mail = mail.downcase }
    validates :name, presence: true ,length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :mail, presence: true ,length: { maximum: 200 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 8 }
    validates :lab, presence: true 
   
   def Employee.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
   end
   
   # Returns a random token.
  def Employee.new_token
    SecureRandom.urlsafe_base64
  end
   
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = Employee.new_token
    update_attribute(:remember_digest, Employee.digest(remember_token))
  end
  
   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
    has_many :lendings
    
    belongs_to :lab
    has_many :devices, through: :lab
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_employee
  before_action :logged_in_admin
  before_action :correct_employee,   only: [:edit, :update]
  before_action :set_employee,       only: [:show, :edit, :update, :destroy]
  before_action :admin_employee,     only: :destroy

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
   @employees = Employee.find(params[:id])
  end

  # GET /employees/new
  def new
    @lab_options = Lab.all.map{|l| [ l.name, l.id ] }
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @lab_options = Lab.all.map{|l| [ l.name, l.id ] }
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.lab =  Lab.find(params[:lab_id])

    respond_to do |format|
      if @employee.save
        #log_in @employee
        flash[:success] = "Welcome to the DeviceTracker App!"
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        
        format.json { render :show, status: :created, location: @employee }
      else
        @lab_options = Lab.all.map{|l| [ l.name, l.id ] }
        format.html { render :new , notice: 'test' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @lab_options = Lab.all.map{|l| [ l.name, l.id ] }
    @employee.lab =  Lab.find(params[:lab_id])
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @has_active_lendings = false
    Lending.all.each do |lending|
      @has_active_lendings ||= lending.employee == @employee
    end
    
    if !@has_active_lendings
      @employee.destroy
      respond_to do |format|
        format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to employees_url, notice: 'Employee cannot be destroyed as long as he/she has lendings!' }
        format.json { head :no_content }
      end
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :mail, :lab_id, :password, :password_confirmation)
    end
    
    # Confirms the correct employee.
    def correct_employee
      @employee = Employee.find(params[:id])
      #redirect_to(root_url) unless current_employee?(@employee)
    end
    
    
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
  <div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@employee) do |f| %>
    
    <%= render partial: "shared/error_messages", locals: {zone: @employee} %>
    
      <form role="form">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Name</span>
            <%= f.text_field :name, :placeholder => "Username", class:"form-control"%>
          </div>
        </div>
      
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">E-Mail</span>
            <%= f.email_field :mail, :placeholder => "E-Mail", class:"form-control"%>
          </div>
        </div>
      
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Password</span>
            <%= f.password_field :password, :placeholder => "Password", type:"password", class:"form-control", id:"pwd" %>
          </div>
        </div>
      
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Confirm</span>
            <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", type:"password", class:"form-control", id:"pwd" %>
          </div>
        </div>
        
        <div class="form-group">
          <%= f.label :lab_id %><br>
          <%= select_tag "lab_id", options_for_select(@lab_options), class: 'form-control' %>
        </div>
      
        <%= f.submit "Apply", class: "btn btn-lg btn-danger btn-block" %>
      </form>
    <% end %>
  </div>
</div>
  
  

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee, class: "btn btn-xs btn-default"   %>
<%= link_to 'Back', employees_path, class: "btn btn-xs btn-default"   %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Lab</th>
      <th colspan="3" class="center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        
        <td><%= employee.mail %></td>
        <% if employee.lab != nil %>
          <td><%= link_to employee.lab.name, employee.lab %></td>
        <% end %>
        
        <td id="rud-bar"><div class="btn-group right" role="group" aria-label="rud">
          <%= link_to 'Show', employee, class: "btn btn-sm btn-default" %>
          <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-sm btn-default" %>
          <% if current_employee.admin? && !current_employee?(employee) %>
            <%= link_to "Destroy", employee, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class: "btn btn-lg btn-danger" %>

app/views/employees/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path, class: "btn btn-xs btn-default"   %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @employee.mail %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @employee.lab.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee), class: "btn btn-xs btn-default"  %>
<%= link_to 'Back', employees_path, class: "btn btn-xs btn-default"  %>