config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'

  resources :labs

  resources :devices

  resources :employees

  resources :lendings
  resources :lenders  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'employees_controller#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]

end

app/models/lending.rb
class DateValidator < ActiveModel::Validator
  def validate(record)
    if record.end <= record.start
      record.errors[:base] << "End date must be later than start"
    end
  end
end

class Lending < ActiveRecord::Base
    belongs_to :lender
    belongs_to :device
    belongs_to :lab
    belongs_to :employee
    
    
    

  def lender_name
    lender.name if lender
  end

  def lender_name=(name)
    self.lender = Lender.find_or_create_by_name(name) unless name.blank?
  end
  
  validates_with DateValidator
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController
  before_action :set_lending, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_employee
    
    
  
  # GET /lendings
  # GET /lendings.json
  def index
    @lendings = Lending.all
    @devices = Device.all.select{|device| device.lab == current_employee.lab}
    @lendings_devices = Array.new()
    Lending.all.each do |lending|
      @lendings_devices << lending.device
    end
    @device_options = @devices - @lendings_devices
    @lender_options = Lender.all
  end

  # GET /lendings/1
  # GET /lendings/1.json
  def show
  end
  # GET /lendings/new
  def new
    @lending = Lending.new
    
    @devices = Device.all.select{|device| device.lab == current_employee.lab}
    @lendings_devices = Array.new()
    Lending.all.each do |lending|
      @lendings_devices << lending.device
    end
    @device_options = @devices - @lendings_devices
    @device_options = @device_options.map{|g| [g.name, g.id]}
    
    @lender_options = Lender.all.map{|l| [ l.name, l.id ] }
    @lending = Lending.new
    
    @lending.start = Date.today
    @lending.end = Date.tomorrow
  end

  # GET /lendings/1/edit
  def edit
    @device_options = Device.all.map{|g| [g.name, g.id]}
    Lending.all.each do |lending|
      @device_options.delete([lending.device.name, lending.device_id])
    end
    @device_options.insert(0, [@lending.device.name, @lending.device.id])
    @lender_options = Lender.all.map{|l| [ l.name, l.id ] }
  end

  # POST /lendings
  # POST /lendings.json
  def create
    @lending = Lending.new(lending_params)
    @lending.employee = current_employee
   #@lending.lab =  Lab.find(params[:lab_id])
    @lending.lab = current_employee.lab
    @lending.device = Device.find(params[:device_id])
    @lending.lender = Lender.find(params[:lender_id])
    
    if @lending.lender == nil
      redirect_to lender_new
    end

    respond_to do |format|
      if @lending.save
        format.html { redirect_to @lending, notice: 'Lending was successfully created.' }
        format.json { render :show, status: :created, location: @lending }
      else
        format.html { render :new }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lendings/1
  # PATCH/PUT /lendings/1.json
  def update
    @lending.employee = current_employee
   #@lending.lab =  Lab.find(params[:lab_id])
    @lending.lab = current_employee.lab
    @lending.device = Device.find(params[:device_id])
    @lending.lender = Lender.find(params[:lender_id])
    
    respond_to do |format|
      if @lending.update(lending_params)
        format.html { redirect_to @lending, notice: 'Lending was successfully updated.' }
        format.json { render :show, status: :ok, location: @lending }
      else
        format.html { render :edit }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lendings/1
  # DELETE /lendings/1.json
  def destroy
    @lending.destroy
    respond_to do |format|
      format.html { redirect_to lendings_url, notice: 'Lending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lending
      @lending = Lending.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lending_params
      params.require(:lending).permit(:start, :end, :device_id, :lab_id, :employee_id, :lender_id)
    end
    
    
    
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/lendings/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
<%= form_for(@lending) do |f| %>
  <%= render partial: "shared/error_messages", locals: {zone: @lending} %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><strong> Duration</strong>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
      </h3>
    </div>
    
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label "From" %>
            <%= f.text_field :start, :type =>"date" , :placeholder => "From", class:"form-control"%>
          </div>
        </div>
    
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label "To" %>
            <%= f.text_field :end, :type =>"date" , :placeholder => "To", class:"form-control"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><strong> Lending </strong>
        <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
      </h3>
    </div>
    
    <div class="panel-body">
      <div class="row">
        
        <div class="col-sm-6">
      <div class="form-group">
        <label for="lending_device_id">Device <span class="glyphicon glyphicon-phone" aria-hidden="true"></span></label><br>
        <%= select_tag "device_id", options_for_select(@device_options), class: 'form-control' %>
      </div>
    </div>
  
  
    <div class="col-sm-6">
      <div class="form-group">
        <label for="lending_lender_id">Borrower <span class="glyphicon glyphicon-education" aria-hidden="true"></span></label><br>
        <%= select_tag "lender_id", options_for_select(@lender_options), class: 'form-control' %>
      </div>
    </div>
  
      </div>
    </div>
  </div>
  
  
    


 <div class="row">
   <div class="col-sm-12">
      <div class="actions">
        <%= f.submit "Apply", class: "btn btn-lg btn-danger btn-block" %>
      </div>
    </div>
  </div>
  
<% end %>
</div>
</div>

app/views/lendings/edit.html.erb
<h1>Editing Lending</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @lending , class: "btn btn-xs btn-default" %>
<%= link_to 'Back', lendings_path, class: "btn btn-xs btn-default"  %>

app/views/lendings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lendings</h1>
  
<table class="table table-hover">
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Device</th>
      <th>Lab</th>
      <th>Employee</th>
      <th>Lender</th>
      <th colspan="3" class="center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @lendings.each do |lending| %>
      <tr>
        <td><%= lending.start %></td>
        <td><%= lending.end %></td>
        <td><%= link_to lending.device.name, lending.device%></td>
        <td><%= link_to lending.lab.name, lending.lab %></td>
        <td><%= link_to lending.employee.name, lending.employee %></td>
        <td><%= link_to lending.lender.name, lending.lender %></td>
        <td id="rud-bar"><div class="btn-group right" role="group" aria-label="rud">
          <%= link_to 'Show', lending, class: "btn btn-sm btn-default" %>
          <%= link_to 'Edit', edit_lending_path(lending), class: "btn btn-sm btn-default" %>
          <% if (current_employee.admin?) || current_employee==lending.employee%>
            <%= link_to "Destroy", lending, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @device_options.any? %>
  <% if @lender_options.any? %>
      <%= link_to 'New Lending', new_lending_path, class: "btn btn-lg btn-danger" %>
  <% else %>
    <h4>There is no one to lend something to. To create a borrower click 
    <%= link_to 'here', new_lender_path, class: "btn btn-xs btn-default" %></h4>
  <% end %>
<% else %>
  <h4>There are no devices left. To create one click 
  <%= link_to 'here', new_device_path, class: "btn btn-xs btn-default" %></h4>
<% end %>

app/views/lendings/new.html.erb
<h1>New Lending</h1>

<%= render 'form' %>

<%= link_to 'Back', lendings_path, class: "btn btn-xs btn-default" %>

app/views/lendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @lending.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @lending.end %>
</p>

<p>
  <strong>Device:</strong>
  <%= @lending.device.name %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @lending.lab.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @lending.employee.name %>
</p>

<p>
  <strong>Lender:</strong>
  <%= @lending.lender.name %>
</p>

<%= link_to 'Edit', edit_lending_path(@lending), class: "btn btn-xs btn-default"  %>
<%= link_to 'Back', lendings_path, class: "btn btn-xs btn-default"  %>