config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'

  resources :labs

  resources :devices

  resources :employees

  resources :lendings
  resources :lenders  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'employees_controller#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]

end

app/models/lab.rb
class Lab < ActiveRecord::Base
    validates :name, presence: true ,length: { maximum: 50 },uniqueness: { case_sensitive: false }
        
    
    has_many :employees
    has_many :devices
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_lab, only: [:show, :edit, :update, :destroy]
    before_action :logged_in_employee
    before_action :logged_in_admin
    

  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
  end

  # GET /labs/new
  def new
    @lab = Lab.new
  end

  # GET /labs/1/edit
  def edit
  end

  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(lab_params)

    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render :show, status: :created, location: @lab }
      else
        format.html { render :new }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labs/1
  # PATCH/PUT /labs/1.json
  def update
    respond_to do |format|
      if @lab.update(lab_params)
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @lab }
      else
        format.html { render :edit }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @has_active_lendings = false
    Lending.all.each do |lending|
      @has_active_lendings ||= lending.lab == @lab
    end
    
    @has_active_employees = false
    Employee.all.each do |employee|
      @has_active_employees ||= employee.lab == @lab
    end
    
    @has_active_devices = false
    Device.all.each do |device|
      @has_active_devices ||= device.lab == @lab
    end
    
    if !@has_active_lendings && !@has_active_employees && !@has_active_devices
      @lab.destroy
      respond_to do |format|
        format.html { redirect_to labs_url, notice: 'Lab was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to labs_url, notice: 'Lab cannot be destroyed as long as it has lendings, employees or devices!' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab
      @lab = Lab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lab_params
      params.require(:lab).permit(:name)
    end
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/views/labs/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

<%= form_for(@lab) do |f| %>
  
  <%= render partial: "shared/error_messages", locals: {zone: @lab} %>

<form role="form">
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">Name</span>
      <%= f.text_field :name, :placeholder => "Lab", class:"form-control"%>
      </div>
    </div>
  <div class="actions">
    <%= f.submit "Apply", class: "btn btn-lg btn-danger btn-block" %>
  </div>
</form>
<% end %>
</div>
</div>

app/views/labs/edit.html.erb
<h1>Editing Lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab, class: "btn btn-xs btn-default"   %>
<%= link_to 'Back', labs_path, class: "btn btn-xs btn-default"   %>

app/views/labs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Labs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3" class="center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @labs.each do |lab| %>
      <tr>
        <td><%= lab.name %></td>
        <td id="rud-bar"><div class="btn-group right" role="group" aria-label="rud">
          <%= link_to 'Show', lab, class: "btn btn-sm btn-default" %>
          <%= link_to 'Edit', edit_lab_path(lab), class: "btn btn-sm btn-default" %>
          <% if current_employee.admin? %>
          <%= link_to "Destroy", lab, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm btn-danger" %>
        <% end %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lab', new_lab_path, class: "btn btn-lg btn-danger" %>

app/views/labs/new.html.erb
<h1>New Lab</h1>

<%= render 'form' %>

<%= link_to 'Back', labs_path, class: "btn btn-xs btn-default" %>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lab.name %>
</p>

<%= link_to 'Edit', edit_lab_path(@lab), class: "btn btn-xs btn-default"   %>
<%= link_to 'Back', labs_path, class: "btn btn-xs btn-default"   %>