config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'

  resources :labs

  resources :devices

  resources :employees

  resources :lendings
  resources :lenders  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'employees_controller#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Devicemanagement System of the
    <a href="http://www.fh-stralsund.de/">Stralsund University of applied Sciences</a>
  </small>
  
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="mailto:<%= Employee.find(admin = true).mail.to_s %>">Contact</a></li>
    </ul>
  </nav>
  <br><%= link_to image_tag("logo.png", alt: "FH-Stralsund Logo", id: "logo"), 'http://www.fh-stralsund.de/' %>
</footer>

app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse">-->
<header class="navbar navbar-fixed-top navbar-inverse", id="navbar-red">
  <div class="container">
      
    
    <nav>
      
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
          <%= link_to "Device Tracker", root_path, id: "logo" %>
        </div>
        
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href=<%=root_path%>><span class="glyphicon glyphicon-home"></span> Home</a></li>
            
            <% if logged_in? %>
            
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu", id="dropdown-red">
              <li><%= link_to "Profile", current_employee %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
            <% if current_employee.admin? %>
             <li><a href=<%=employees_path%>><span class="glyphicon glyphicon-user"></span> Employees</a></li>
             <li><a href=<%=labs_path%>><span class="glyphicon glyphicon-blackboard"></span> Labs</a></li>
          <% end %>
            <li><a href=<%=devices_path%>><span class="glyphicon glyphicon-phone"></span> Devices</a></li>
            <li><a href=<%=lendings_path%>><span class="glyphicon glyphicon-calendar"></span> Lendings</a></li>
            <li><a href=<%=lenders_path%>><span class="glyphicon glyphicon-education"></span> Borrowers</a></li>
          </li>
        <% else %>
          <li><a href=<%=login_path%>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div>
      </div>
      
    </nav>
    
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>